// Maps college name -> /logos/colleges/{slug}.png
const COLLEGE_SLUG = {
  // ── Power conferences ───────────────────────────────────────────
  'Alabama':                    'alabama',
  'Arizona':                    'arizona',
  'Arizona State':              'arizona-state',
  'Arkansas':                   'arkansas',
  'Auburn':                     'auburn',
  'Baylor':                     'baylor',
  'Boston College':             'boston-college',
  'BYU':                        'byu',
  'California':                 'california',
  'Clemson':                    'clemson',
  'Colorado':                   'colorado',
  'Colorado State':             'colorado-state',
  'Duke':                       'duke',
  'East Carolina':              'east-carolina',
  'Florida':                    'florida',
  'Florida State':              'florida-state',
  'Georgia':                    'georgia',
  'Georgia Tech':               'georgia-tech',
  'Hawaii':                     'hawaii',
  'Illinois':                   'illinois',
  'Indiana':                    'indiana',
  'Iowa':                       'iowa',
  'Iowa State':                 'iowa-state',
  'Kansas':                     'kansas',
  'Kansas State':               'kansas-state',
  'Kentucky':                   'kentucky',
  'Louisiana':                  'louisiana',
  'Louisiana State':            'lsu',
  'Louisiana Tech':             'louisiana-tech',
  'Louisville':                 'louisville',
  'LSU':                        'lsu',
  'Maryland':                   'maryland',
  'Miami':                      'miami',
  'Michigan':                   'michigan',
  'Michigan State':             'michigan-state',
  'Minnesota':                  'minnesota',
  'Mississippi':                'ole-miss',
  'Mississippi State':          'mississippi-state',
  'Mississippi Valley State':   'mississippi-valley-state',
  'Missouri':                   'missouri',
  'N.C. State':                 'nc-state',
  'NC State':                   'nc-state',
  'Northwestern':               'northwestern',
  'North Carolina':             'north-carolina',
  'North Carolina State':       'nc-state',
  'North Dakota State':         'north-dakota-state',
  'Nebraska':                   'nebraska',
  'Nevada':                     'nevada',
  'Notre Dame':                 'notre-dame',
  'Ohio':                       'ohio',
  'Ohio State':                 'ohio-state',
  'Oklahoma':                   'oklahoma',
  'Oklahoma State':             'oklahoma',
  'Oklahoma State':             'oklahoma-state',
  'Ole Miss':                   'ole-miss',
  'Oregon':                     'oregon',
  'Oregon State':               'oregon-state',
  'Penn State':                 'penn-state',
  'Pittsburgh':                 'pittsburgh',
  'Purdue':                     'purdue',
  'Rutgers':                    'rutgers',
  'South Carolina':             'south-carolina',
  'Stanford':                   'stanford',
  'Syracuse':                   'syracuse',
  'TCU':                        'tcu',
  'Tennessee':                  'tennessee',
  'Texas':                      'texas',
  'Texas A&M':                  'texas-am',
  'Texas Tech':                 'texas-tech',
  'Toledo':                     'toledo',
  'Troy':                       'troy',
  'UCLA':                       'ucla',
  'USC':                        'usc',
  'Southern California':        'usc',
  'Utah':                       'utah',
  'Utah State':                 'utah-state',
  'Vanderbilt':                 'vanderbilt',
  'Virginia':                   'virginia',
  'Virginia Tech':              'virginia-tech',
  'Wake Forest':                'wake-forest',
  'Washington':                 'washington',
  'Washington State':           'washington-state',
  'West Virginia':              'west-virginia',
  'Wisconsin':                  'wisconsin',
  'Wyoming':                    'wyoming',
  // ── Group of 5 / mid-major ──────────────────────────────────────
  'Akron':                      'akron',
  'Appalachian State':          'appalachian-state',
  'Arkansas State':             'arkansas-state',
  'Army':                       'army',
  'Ball State':                 'ball-state',
  'Boise State':                'boise-state',
  'Bowling Green':              'bowling-green',
  'Buffalo':                    'buffalo',
  'Central Michigan':           'central-michigan',
  'Cincinnati':                 'cincinnati',
  'Coastal Carolina':           'coastal-carolina',
  'Connecticut':                'connecticut',
  'Delaware':                   'delaware',
  'East Carolina':              'east-carolina',
  'Eastern Illinois':           'eastern-illinois',
  'Eastern Kentucky':           'eastern-kentucky',
  'Eastern Michigan':           'eastern-michigan',
  'Eastern Washington':         'eastern-washington',
  'Florida Atlantic':           'florida-atlantic',
  'Florida International':      'florida-international',
  'Florida A&M':                'florida-am',
  'Fresno State':               'fresno-state',
  'Georgia Southern':           'georgia-southern',
  'Harvard':                    'harvard',
  'Houston':                    'houston',
  'Idaho':                      'idaho',
  'Illinois State':             'illinois-state',
  'James Madison':              'james-madison',
  'Kent State':                 'kent-state',
  'Liberty':                    'liberty',
  'Louisiana':                  'louisiana',
  'Louisiana Tech':             'louisiana-tech',
  'Louisiana-Lafayette':        'louisiana',
  'Louisiana-Monroe':           'louisiana-monroe',
  'Marshall':                   'marshall',
  'Memphis':                    'memphis',
  'Miami (Ohio)':               'miami-ohio',
  'Middle Tennessee':           'middle-tennessee',
  'Middle Tennessee State':     'middle-tennessee',
  'Montana':                    'montana',
  'Navy':                       'navy',
  'Nevada':                     'nevada',
  'New Mexico':                 'new-mexico',
  'New Mexico State':           'new-mexico-state',
  'North Carolina A&T':         'nc-at',
  'North Dakota State':         'north-dakota-state',
  'North Texas':                'north-texas',
  'Northern Illinois':          'northern-illinois',
  'Ohio':                       'ohio',
  'Old Dominion':               'old-dominion',
  'Rice':                       'rice',
  'Sacramento State':           'sacramento-state',
  'Sam Houston State':          'sam-houston-state',
  'San Diego State':            'san-diego-state',
  'San Jose State':             'san-jose-state',
  'SMU':                        'smu',
  'South Alabama':              'south-alabama',
  'South Dakota State':         'south-dakota-state',
  'South Florida':              'south-florida',
  'Southern Illinois':          'southern-illinois',
  'Southern Miss':              'southern-miss',
  'Southern Mississippi':       'southern-miss',
  'South Carolina State':       'south-carolina-state',
  'Stephen F. Austin State':    'stephen-f-austin',
  'Temple':                     'temple',
  'Toledo':                     'toledo',
  'Troy':                       'troy',
  'Tulane':                     'tulane',
  'Tulsa':                      'tulsa',
  'UAB':                        'uab',
  'UCF':                        'ucf',
  'Central Florida':            'ucf',
  'UMass Amherst':              'umass',
  'UNLV':                       'unlv',
  'University of South Florida':'south-florida',
  'UTEP':                       'utep',
  'Texas-El Paso':              'utep',
  'Villanova':                  'villanova',
  'Western Carolina':           'western-carolina',
  'Western Kentucky':           'western-kentucky',
  'Western Michigan':           'western-michigan',
  'Wyoming':                    'wyoming',
  'Youngstown State':           'youngstown-state',
  // ── HBCUs ───────────────────────────────────────────────────────
  'Grambling':                  'grambling',
  'Grambling State':            'grambling',
  // ── FCS / Mid-major with ESPN logos ────────────────────────────
  'Air Force':                  'air-force',
  'Cal State Northridge':       'cal-state-northridge',
  'CSUN':                       'cal-state-northridge',
  'California State Northridge':'cal-state-northridge',
  'Grand Valley State':         'grand-valley',
  'Montana State':              'montana-state',
  'Presbyterian':               'presbyterian',
  'Presbyterian College':       'presbyterian',
  'Saint Francis':              'saint-francis',
  'St. Francis (PA)':           'saint-francis',
  'St. Francis':                'saint-francis',
  'Southeast Louisiana':        'southeast-louisiana',
  'Union':                      'union',
  'Union College':              'union',
  'VMI':                        'virginia-military',
  'Virginia Military Institute':'virginia-military',
  'William Penn':               'william-penn',
  'William Penn University':    'william-penn',
  'Alabama State':              'alabama-state',
  'Alcorn State':               'alcorn-state',
  'Brown':                      'brown',
  'Colgate':                    'colgate',
  'Cornell':                    'cornell',
  'Dartmouth':                  'dartmouth',
  'Delaware State':             'delaware-state',
  'East Tennessee State':       'east-tennessee-state',
  'Fordham':                    'fordham',
  'Furman':                     'furman',
  'Hampton':                    'hampton',
  'Holy Cross':                 'holy-cross',
  'Howard':                     'howard',
  'Idaho State':                'idaho-state',
  'Indiana State':              'indiana-state',
  'Jackson State':              'jackson-state',
  'Jackson State University':   'jackson-state',
  'Jacksonville State':         'jacksonville-state',
  'Maine':                      'maine',
  'McNeese State':              'mcneese-state',
  'Murray State':               'murray-state',
  'New Hampshire':              'new-hampshire',
  'Nicholls State':             'nicholls-state',
  'Norfolk State':              'norfolk-state',
  'North Alabama':              'north-alabama',
  'North Carolina Central':     'north-carolina-central',
  'North Dakota':               'north-dakota',
  'Northern Arizona':           'northern-arizona',
  'Northern Iowa':              'northern-iowa',
  'Penn':                       'penn',
  'Portland State':             'portland-state',
  'Prairie View A&M':           'prairie-view-am',
  'Princeton':                  'princeton',
  'Rhode Island':               'rhode-island',
  'Richmond':                   'richmond',
  'Samford':                    'samford',
  'South Dakota':               'south-dakota',
  'Southeastern Louisiana':     'southeastern-louisiana',
  'Southern':                   'southern',
  'Tennessee State':            'tennessee-state',
  'Tennessee-Chattanooga':      'tennessee-chattanooga',
  'Chattanooga':                'tennessee-chattanooga',
  'The Citadel':                'the-citadel',
  'Towson':                     'towson',
  'Towson State':               'towson',
  'UC Davis':                   'uc-davis',
  'Weber State':                'weber-state',
  'Western Illinois':           'western-illinois',
  'William & Mary':             'william-and-mary',
  'Wofford':                    'wofford',
  'Yale':                       'yale',
  'Incarnate Word':             'incarnate-word',
  'Marist':                     'marist',
  'Stony Brook':                'stony-brook',
  'Saginaw Valley State':       'saginaw-valley-st',
  'Albany':                     'albany',
  'Austin Peay':                'austin-peay',
  'Bethune-Cookman':            'bethune-cookman',
  'Bethune-Cookman College':    'bethune-cookman',
  'Bloomsburg':                 'bloomsburg',
  'Bradley University':         'bradley',
  'Cal Poly (San Luis Obispo)': 'cal-poly-slo',
  'Charleston':                 'charleston',
  'Charlotte':                  'charlotte',
  'Dayton':                     'dayton',
  'Drake':                      'drake',
  'Duquesne':                   'duquesne',
  'Elon':                       'elon',
  'Georgia State':              'georgia-state',
  'Hofstra':                    'hofstra',
  'Jacksonville':               'jacksonville',
  'Lafayette College':          'lafayette',
  'Lindenwood':                 'lindenwood',
  'Minnesota State':            'minnesota-state',
  'Monmouth':                   'monmouth',
  'Monmouth College':           'monmouth',
  'Morgan State':               'morgan-state',
  'Northern Colorado':          'northern-colorado',
  'Northwestern State (LA)':    'northwestern-state',
  'Northwestern State':         'northwestern-state',
  'Missouri State':             'missouri-state',
  'Sacred Heart University':    'sacred-heart',
  'Sacred Heart':               'sacred-heart',
  'San Diego':                  'san-diego',
  'Santa Clara University':     'santa-clara',
  'Southeast Missouri State':   'southeast-missouri',
  'Stetson':                    'stetson',
  'Tennessee-Martin':           'tennessee-martin',
  'Texas Southern':             'texas-southern',
  'Texas State-San Marcos':     'texas-state',
  'Texas-San Antonio':          'texas-san-antonio',
  'UC Irvine':                  'uc-irvine',
  'Valparaiso':                 'valparaiso',
  'Virginia State':             'virginia-state',
  'Washburn':                   'washburn',
  'Wayne State':                'wayne-state',
  'Wayne State College':        'wayne-state',
  'West Alabama':               'west-alabama',
  'West Georgia':               'west-georgia',
  'West Texas State':           'west-texas',
  'Winston Salem State University': 'winston-salem',
  'Winston-Salem State':        'winston-salem',
  'Gardner-Webb':               'gardner-webb',
  'NW Missouri State University': 'northwest-missouri',
  // ── Alternate/historical spellings ──────────────────────────────
  'Texas A & M':                'texas-am',
  'Louisiana Lafayette':        'louisiana',
  'Miami (FL)':                 'miami',
}

/**
 * Returns the path to a college logo PNG, or null if not found
 */
export function collegeLogo(collegeName) {
  if (!collegeName) return null
  // Try exact match
  const slug = COLLEGE_SLUG[collegeName]
  if (slug) return `/logos/colleges/${slug}.png`
  // Case-insensitive fallback
  const lower = collegeName.toLowerCase()
  for (const [name, s] of Object.entries(COLLEGE_SLUG)) {
    if (name.toLowerCase() === lower) return `/logos/colleges/${s}.png`
  }
  return null
}
